<a href="https://colab.research.google.com/github/AndreLYL/Tensorflow-learning/blob/master/Udacity_Tensorflow_tutorial_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python基本使用

In [0]:
print("Hello World! I am Andre.") # 注意大小写，尼玛刚刚没注意是大写的P，一直报错
print("博学之，审问之，慎思之，笃行之") # 中文测试

Hello World! I am Andre.
博学之，审问之，慎思之，笃行之


In [0]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("Hello World, x was < 10 ")
  elif (x < 20):
    print("Hello World, x was < 20 ")
  else:
    print("Hello World, x was >= 20 ")
  return x + y


for i in range(8, 25, 5): # i的范围(8, 25)，步长5
  print ("--- Now running with i: {}".format(i))  # 格式化字符串的函数 str.format()，它增强了字符串格式化的功能。基本语法是通过 {} 和 : 来代替以前的 % 。
  r = HelloWorldXY(i, i)
  print("Result from HelloWorld: {}".format(i, r))

--- Now running with i: 8
Hello World, x was < 10 
Result from HelloWorld: 8
--- Now running with i: 13
Hello World, x was < 20 
Result from HelloWorld: 13
--- Now running with i: 18
Hello World, x was < 20 
Result from HelloWorld: 18
--- Now running with i: 23
Hello World, x was >= 20 
Result from HelloWorld: 23


In [0]:
print(HelloWorldXY(1,2))

Hello World, x was < 10 
3


In [0]:
print("Iterate over the items. 'Range(2)' is like a list [0, 1]")
for i in range(2):
  print(i)

print("Iterate over an actual list.")
for i in [0, 1]:                     # 列表用的是中括号
  print(i)

print("While works")
i = 0
while i < 2:
  print(i)
  i += 1





Iterate over the items. 'Range(2)' is like a list [0, 1]
0
1
Iterate over an actual list.
0
1
While works
0
1


# Numpy and lists

Numpy库用于科学计算 



1.   **enumerate()：** 函数用于将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，同时列出数据和数据下标，一般用在 for 循环当中。[参考](https://www.runoob.com/python/python-func-enumerate.html)
2.   **format()：** [函数用法](https://www.runoob.com/python/att-string-format.html)



In [0]:
import numpy as np  # Make numpy avaliable using np.

#create a numpy array, and append an element （append: 附加，添加）
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [0]:
#Numpy基本的数组函数：最大值，平均数，返回最大值的对应索引

print("\nShowing some basic math on arrays")
b = np.array([0, 1, 4, 3, 2])                              # 这里不要忘记中括号，否则会报错
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))



Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [0]:
# 可以通过print函数直接输出变量的格式
print("\nYou can print the type of anything")
print("Type of a: {}, Type of a[0]: {}".format(type(a), type(a[0])))
print("Type of b: {}, Type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of a: <class 'numpy.ndarray'>, Type of a[0]: <class 'numpy.str_'>
Type of b: <class 'numpy.ndarray'>, Type of b[0]: <class 'numpy.int64'>


In [0]:
print("\nUse Numpy to create a [3, 3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use Numpy to create a [3, 3] dimension array with random number
[[0.22124139 0.84426881 0.01343631]
 [0.42296266 0.43942379 0.73877804]
 [0.83286699 0.03307905 0.08876508]]


In [0]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


# Colab Specifics
Colab是一个虚拟机，在Shell命令前面加上感叹号就能直接运行这些命令

In [0]:
print("\nDoing $ls on filesystem")
!ls -l # 这里是字母L，不是数字1
!pwd


Doing $ls on filesystem
total 4
drwxr-xr-x 1 root root 4096 Feb  5 18:37 sample_data
/content


In [0]:
print("Install numpy")
!pip install numpy

Install numpy


## Exercise 1

In [0]:
print("1. List the path of the current directory")
!pwd
print("2. Go to / (cd) and list the content (ls -l)")
!cd /
!ls -l

1. List the path of the current directory
/content
2. Go to / (cd) and list the content (ls -l)
total 4
drwxr-xr-x 1 root root 4096 Feb  5 18:37 sample_data


All usage of Colab in this course is completely free or charge. Even GPU usage is provided free of charge for some hours of usage every day.

**Using GPUs**
* Many of the exercises in the course executes more quickly by using GPU runtime: Runtime | Change runtime type | Hardware accelerator | GPU

**Some final words on Colab**
*   You execute each cell in order, you can edit & re-execute cells if you want
*   Sometimes, this could have unintended consequences. For example, if you add a dimension to an array and execute the cell multiple times, then the cells after may not work. If you encounter problem reset your environment:
  *   Runtime -> Restart runtime... Resets your Python shell
  *   Runtime -> Restart all runtimes... Will reset the Colab image, and get you back to a 100% clean environment
* You can also clear the output in the Colab by doing: Edit -> Clear all outputs
* Colabs in this course are loaded from GitHub. Save to your Google Drive if you want a copy with your code/output: File -> Save a copy in Drive...

**Learn More**
*   Check out [this](https://www.youtube.com/watch?v=inN8seMm7UI&list=PLQY2H8rRoyvwLbzbnKJ59NkZvQAW9wLbx&index=3) episode of #CodingTensorFlow, and don't forget to subscribe to the YouTube channel ;)
